# Generated by Django 2.1 on 2019-01-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100, unique=True)),
                ('task_description', models.TextField()),
                ('task_status', models.CharField(choices=[('PARKED', 'Parked'), ('STARTED', 'Started'), ('FINISHED', 'Finished')], max_length=100)),
            ],
        ),
    ]
